/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HypixelRouteRouteImport } from './routes/hypixel/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HypixelIndexRouteImport } from './routes/hypixel/index'
import { Route as HypixelPlayersRouteImport } from './routes/hypixel/players'
import { Route as HypixelPlayersIndexRouteImport } from './routes/hypixel/players.index'
import { Route as HypixelPlayersUsernameRouteImport } from './routes/hypixel/players.$username'

const HypixelRouteRoute = HypixelRouteRouteImport.update({
  id: '/hypixel',
  path: '/hypixel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HypixelIndexRoute = HypixelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HypixelRouteRoute,
} as any)
const HypixelPlayersRoute = HypixelPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => HypixelRouteRoute,
} as any)
const HypixelPlayersIndexRoute = HypixelPlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HypixelPlayersRoute,
} as any)
const HypixelPlayersUsernameRoute = HypixelPlayersUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => HypixelPlayersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hypixel': typeof HypixelRouteRouteWithChildren
  '/hypixel/players': typeof HypixelPlayersRouteWithChildren
  '/hypixel/': typeof HypixelIndexRoute
  '/hypixel/players/$username': typeof HypixelPlayersUsernameRoute
  '/hypixel/players/': typeof HypixelPlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hypixel': typeof HypixelIndexRoute
  '/hypixel/players/$username': typeof HypixelPlayersUsernameRoute
  '/hypixel/players': typeof HypixelPlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hypixel': typeof HypixelRouteRouteWithChildren
  '/hypixel/players': typeof HypixelPlayersRouteWithChildren
  '/hypixel/': typeof HypixelIndexRoute
  '/hypixel/players/$username': typeof HypixelPlayersUsernameRoute
  '/hypixel/players/': typeof HypixelPlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hypixel'
    | '/hypixel/players'
    | '/hypixel/'
    | '/hypixel/players/$username'
    | '/hypixel/players/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hypixel' | '/hypixel/players/$username' | '/hypixel/players'
  id:
    | '__root__'
    | '/'
    | '/hypixel'
    | '/hypixel/players'
    | '/hypixel/'
    | '/hypixel/players/$username'
    | '/hypixel/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HypixelRouteRoute: typeof HypixelRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hypixel': {
      id: '/hypixel'
      path: '/hypixel'
      fullPath: '/hypixel'
      preLoaderRoute: typeof HypixelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hypixel/': {
      id: '/hypixel/'
      path: '/'
      fullPath: '/hypixel/'
      preLoaderRoute: typeof HypixelIndexRouteImport
      parentRoute: typeof HypixelRouteRoute
    }
    '/hypixel/players': {
      id: '/hypixel/players'
      path: '/players'
      fullPath: '/hypixel/players'
      preLoaderRoute: typeof HypixelPlayersRouteImport
      parentRoute: typeof HypixelRouteRoute
    }
    '/hypixel/players/': {
      id: '/hypixel/players/'
      path: '/'
      fullPath: '/hypixel/players/'
      preLoaderRoute: typeof HypixelPlayersIndexRouteImport
      parentRoute: typeof HypixelPlayersRoute
    }
    '/hypixel/players/$username': {
      id: '/hypixel/players/$username'
      path: '/$username'
      fullPath: '/hypixel/players/$username'
      preLoaderRoute: typeof HypixelPlayersUsernameRouteImport
      parentRoute: typeof HypixelPlayersRoute
    }
  }
}

interface HypixelPlayersRouteChildren {
  HypixelPlayersUsernameRoute: typeof HypixelPlayersUsernameRoute
  HypixelPlayersIndexRoute: typeof HypixelPlayersIndexRoute
}

const HypixelPlayersRouteChildren: HypixelPlayersRouteChildren = {
  HypixelPlayersUsernameRoute: HypixelPlayersUsernameRoute,
  HypixelPlayersIndexRoute: HypixelPlayersIndexRoute,
}

const HypixelPlayersRouteWithChildren = HypixelPlayersRoute._addFileChildren(
  HypixelPlayersRouteChildren,
)

interface HypixelRouteRouteChildren {
  HypixelPlayersRoute: typeof HypixelPlayersRouteWithChildren
  HypixelIndexRoute: typeof HypixelIndexRoute
}

const HypixelRouteRouteChildren: HypixelRouteRouteChildren = {
  HypixelPlayersRoute: HypixelPlayersRouteWithChildren,
  HypixelIndexRoute: HypixelIndexRoute,
}

const HypixelRouteRouteWithChildren = HypixelRouteRoute._addFileChildren(
  HypixelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HypixelRouteRoute: HypixelRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
