// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type ApiHypixelPlayersIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/hypixel/controllers/show_player_controller.ts').default['handle'], false>
}
type ApiHypixelGuildsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/hypixel/controllers/show_guild_controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'api': {
    'hypixel': {
      'players': {
        ':username': {
          '$url': {
          };
          '$get': ApiHypixelPlayersIdGetHead;
          '$head': ApiHypixelPlayersIdGetHead;
        };
      };
      'guilds': {
        ':name': {
          '$url': {
          };
          '$get': ApiHypixelGuildsIdGetHead;
          '$head': ApiHypixelGuildsIdGetHead;
        };
      };
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
